name: Autograding Tests
on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SQL Test
        id: sql-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: SQL Test
          setup-command: sqlite3 test.db < create.sql && sqlite3 test.db < insert.sql
          command: sqlite3 test.db < student_solution.sql | diff - expected.txt
          timeout: 5
          max-score: 1

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          SQL-TEST_RESULTS: "${{steps.sql-test.outputs.result}}"
        with:
          runners: sql-test
